### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by DenisKorkmaz** [DenisKorkmaz/Capstone-Project#1]
### Value Proposition
**As a** User  
**I want to** view news articles when I open the app  
**So that** I can stay up-to-date with the latest news.

### Description
The app's home page should display a list of news articles fetched from an API.

### Acceptance Criteria
- [ ] The home page loads and displays a list of news articles.

### Tasks
- [ ] Setup project and necessary dependencies.
- [ ] Choose a suitable news API.
- [ ] Fetch news articles from the API.
- [ ] Display articles on the home page.

### Complexity
S
